Repository mRemoteNG/mRemoteNG, pull requests merged in 2018-10, with the labels that each got.

#951 Clipboard sharing setting implementation for RDP protocol
  mRemoteNGTests/TestHelpers/SerializableConnectionInfoAllPropertiesOfType.cs
  mRemoteNGTests/UI/Window/ConfigWindowTests/ConfigWindowGeneralTests.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/Csv/CsvConnectionsDeserializerMremotengFormat.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/Csv/CsvConnectionsSerializerMremotengFormat.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionNodeSerializer26.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionsDeserializer.cs
  mRemoteV1/Config/Serializers/DataTableDeserializer.cs
  mRemoteV1/Config/Serializers/DataTableSerializer.cs
  mRemoteV1/Config/Serializers/MiscSerializers/RemoteDesktopConnectionDeserializer.cs
  mRemoteV1/Config/Serializers/MiscSerializers/RemoteDesktopConnectionManagerDeserializer.cs
  mRemoteV1/Connection/AbstractConnectionRecord.cs
  mRemoteV1/Connection/ConnectionInfo.cs
  mRemoteV1/Connection/ConnectionInfoInheritance.cs
  mRemoteV1/Connection/Protocol/RDP/RdpProtocol.cs
  mRemoteV1/Properties/Settings.Designer.cs
  mRemoteV1/Properties/Settings.settings
  mRemoteV1/Resources/Language/Language.es.resx
  mRemoteV1/Resources/Language/Language.resx
  mRemoteV1/UI/Window/ConfigWindow.cs
  mRemoteV1/app.config
Labels: Enhancement, Needs Translation

#1129 Update Language.es.resx
  mRemoteV1/Resources/Language/Language.es.resx
Labels: Enhancement

#1145 Fixing "Reconnect to previously opened sessions on startup"
  mRemoteV1/Config/Connections/SaveConnectionsOnEdit.cs
Labels: Bug
