Repository mRemoteNG/mRemoteNG, pull requests merged in 2018-08, with the labels that each got.

#1057 Fixing NullReferenceException when renaming node
  mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
Labels: Bug

#1055 647 save symbols
  Jenkinsfile_publish.groovy
  Tools/github_functions.ps1
  Tools/postbuild_mremotev1.ps1
  Tools/tidy_files_for_release.ps1
  Tools/zip_portable_files.ps1
  Tools/zip_symbols.ps1
  mRemoteV1/mRemoteV1.csproj
Labels: Enhancement, Project Infrastructure

#1072 Update the Russian language
  mRemoteV1/Resources/Language/Language.resx
  mRemoteV1/Resources/Language/Language.ru.resx
Labels: Enhancement

#1016 Chinese simplified language update for latest commit 05c96da
  mRemoteV1/Resources/Language/Language.zh-CN.resx
Labels: Enhancement

#928 Add context menu items to close other and other to the right tabs
  mRemoteV1/Resources/Language/Language.Designer.cs
  mRemoteV1/Resources/Language/Language.resx
  mRemoteV1/Resources/Language/Language.ru.resx
  mRemoteV1/UI/Window/ConnectionWindow.Designer.cs
  mRemoteV1/UI/Window/ConnectionWindow.cs
Labels: Enhancement
