Repository mRemoteNG/mRemoteNG, pull requests merged in 2019-04, with the labels that each got.

#1404 Correct the Chinese translation in https://github.com/mRemoteNG/mRemoteNG/issues/1403
  mRemoteV1/Resources/Language/Language.zh-CN.resx
Labels: Enhancement

#1342 Added option to disable username trimming
  mRemoteV1/Connection/AbstractConnectionRecord.cs
  mRemoteV1/Properties/Settings.Designer.cs
  mRemoteV1/Properties/Settings.settings
  mRemoteV1/Resources/Language/Language.Designer.cs
  mRemoteV1/Resources/Language/Language.de.resx
  mRemoteV1/Resources/Language/Language.resx
  mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.Designer.cs
  mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.cs
  mRemoteV1/app.config
Labels: Enhancement

#1414 Add "Remote Audio Capture" option #383
  mRemoteNGTests/Config/Serializers/ConnectionSerializers/Csv/CsvConnectionsDeserializerMremotengFormatTests.cs
  mRemoteNGTests/TestHelpers/SerializableConnectionInfoAllPropertiesOfType.cs
  mRemoteNGTests/UI/Window/ConfigWindowTests/ConfigWindowGeneralTests.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/Csv/CsvConnectionsDeserializerMremotengFormat.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/Csv/CsvConnectionsSerializerMremotengFormat.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/MsSql/DataTableDeserializer.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/MsSql/DataTableSerializer.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionNodeSerializer27.cs
  mRemoteV1/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionsDeserializer.cs
  mRemoteV1/Config/Serializers/MiscSerializers/RemoteDesktopConnectionDeserializer.cs
  mRemoteV1/Connection/AbstractConnectionRecord.cs
  mRemoteV1/Connection/ConnectionInfo.cs
  mRemoteV1/Connection/ConnectionInfoInheritance.cs
  mRemoteV1/Connection/Protocol/ICA/IcaProtocol.cs
  mRemoteV1/Connection/Protocol/RDP/RdpProtocol.cs
  mRemoteV1/Properties/Settings.Designer.cs
  mRemoteV1/Properties/Settings.settings
  mRemoteV1/Resources/Help/MSSQLScript.txt
  mRemoteV1/Resources/Help/MySQLScript.txt
  mRemoteV1/Resources/Language/Language.Designer.cs
  mRemoteV1/Resources/Language/Language.resx
  mRemoteV1/Schemas/mremoteng_confcons_v2_7.xsd
  mRemoteV1/UI/Window/ConfigWindow.cs
  mRemoteV1/app.config
Labels: Enhancement, Needs Translation

#1389 Refactored config window to make property management easier
  mRemoteNGTests/Connection/ConnectionInfoTests.cs
  mRemoteNGTests/Connection/DefaultConnectionInheritanceTests.cs
  mRemoteNGTests/TestHelpers/ConnectionInfoHelpers.cs
  mRemoteNGTests/TestHelpers/Randomizer.cs
  mRemoteNGTests/UI/Controls/FilteredPropertyGridTests.cs
  mRemoteNGTests/UI/Window/ConfigWindowTests/ConfigWindowGeneralTests.cs
  mRemoteNGTests/UI/Window/ConfigWindowTests/ConfigWindowSpecialTestsBase.cs
  mRemoteNGTests/mRemoteNGTests.csproj
  mRemoteV1/Connection/AbstractConnectionRecord.cs
  mRemoteV1/Connection/ConnectionInfo.cs
  mRemoteV1/Connection/ConnectionInfoInheritance.cs
  mRemoteV1/Connection/DefaultConnectionInfo.cs
  mRemoteV1/Connection/DefaultConnectionInheritance.cs
  mRemoteV1/Container/ContainerInfo.cs
  mRemoteV1/Tools/Attributes/UsedInAllProtocolsExceptAttribute.cs
  mRemoteV1/Tools/Attributes/UsedInProtocolAttribute.cs
  mRemoteV1/UI/Controls/ConnectionInfoPropertyGrid/ConnectionInfoPropertyGrid.Designer.cs
  mRemoteV1/UI/Controls/ConnectionInfoPropertyGrid/ConnectionInfoPropertyGrid.cs
  mRemoteV1/UI/Controls/ConnectionInfoPropertyGrid/PropertyMode.cs
  mRemoteV1/UI/Controls/FilteredPropertyGrid/FilteredPropertyGrid.cs
  mRemoteV1/UI/Window/ConfigWindow.cs
  mRemoteV1/mRemoteV1.csproj
Labels: Enhancement, TechnicalDebt
