Repository mRemoteNG/mRemoteNG, pull requests merged in 2019-03, with the labels that each got.

#1336 Added ability to run External tools on folders
  mRemoteV1/Tools/ExternalTool.cs
  mRemoteV1/UI/Controls/ConnectionContextMenu.cs
Labels: Enhancement

#1344 Help file cleanup
  mRemoteV1/Resources/Help/Index.htm
  mRemoteV1/Resources/Help/Introduction.htm
  mRemoteV1/Resources/Help/Main.css
  mRemoteV1/Resources/Help/Screenshots/Configuration/01.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/02.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/03.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/04.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/05.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/06.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/07.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/08.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/09.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/10.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/11.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/12.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/13.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/14.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/15.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/16.png
  mRemoteV1/Resources/Help/Screenshots/Configuration/17.png
  mRemoteV1/Resources/Help/Screenshots/Main Menu/File.png
  mRemoteV1/Resources/Help/Screenshots/Main Menu/Info.png
  mRemoteV1/Resources/Help/Screenshots/Main Menu/QuickConnect.png
  mRemoteV1/Resources/Help/Screenshots/Main Menu/Tools.png
  mRemoteV1/Resources/Help/Screenshots/Main Menu/View.png
  mRemoteV1/Resources/Help/Screenshots/Quickconnect/01.png
  mRemoteV1/Resources/Help/Screenshots/Quickconnect/02.png
  mRemoteV1/Resources/Help/Screenshots/Quickconnect/03.png
  mRemoteV1/Resources/Help/Screenshots/Reference/config_panel_02.png
  mRemoteV1/Resources/Help/gs_command_line_switches.htm
  mRemoteV1/Resources/Help/gs_installation.htm
  mRemoteV1/Resources/Help/gs_prerequisites.htm
  mRemoteV1/Resources/Help/gs_running_mremoteng.htm
  mRemoteV1/Resources/Help/st_common_problems_rdp.htm
  mRemoteV1/Resources/Help/ui_config.htm
  mRemoteV1/Resources/Help/ui_connections.htm
  mRemoteV1/Resources/Help/ui_external_tools.htm
  mRemoteV1/Resources/Help/ui_file_transfer.htm
  mRemoteV1/Resources/Help/ui_import_and_export.htm
  mRemoteV1/Resources/Help/ui_keyboardshortcuts.htm
  mRemoteV1/Resources/Help/ui_menus.htm
  mRemoteV1/Resources/Help/ui_navigation.htm
  mRemoteV1/Resources/Help/ui_notifications.htm
  mRemoteV1/Resources/Help/ui_options.htm
  mRemoteV1/Resources/Help/ui_port_scan.htm
  mRemoteV1/Resources/Help/ui_quick_connect.htm
  mRemoteV1/Resources/Help/ui_screenshot_manager.htm
  mRemoteV1/Resources/Help/ui_sql_configuration.htm
  mRemoteV1/UI/Window/HelpWindow.cs
  mRemoteV1/mRemoteV1.csproj
Labels: Enhancement

#1340 added missing properties when deserializing .rdp file
  mRemoteV1/Config/Serializers/MiscSerializers/RemoteDesktopConnectionDeserializer.cs
Labels: Bug

#1361 Implemented a view only mode for RDP
  mRemoteV1/Connection/ConnectionInfo.cs
  mRemoteV1/Connection/Protocol/ISupportsViewOnly.cs
  mRemoteV1/Connection/Protocol/RDP/RdpProtocol.cs
  mRemoteV1/Connection/Protocol/VNC/Connection.Protocol.VNC.cs
  mRemoteV1/Resources/Language/Language.Designer.cs
  mRemoteV1/Resources/Language/Language.de.resx
  mRemoteV1/Resources/Language/Language.resx
  mRemoteV1/UI/Controls/ConnectionContextMenu.cs
  mRemoteV1/UI/Window/ConnectionWindow.cs
  mRemoteV1/mRemoteV1.csproj
Labels: Enhancement, Needs Translation

#1339 Add button to clear searchbox
  mRemoteV1/Resources/Language/Language.Designer.cs
  mRemoteV1/Resources/Language/Language.de.resx
  mRemoteV1/Resources/Language/Language.resx
  mRemoteV1/UI/Controls/Base/NGSearchBox.cs
  mRemoteV1/UI/Controls/Base/NGSearchBox.resx
  mRemoteV1/UI/Window/ConnectionTreeWindow.Designer.cs
  mRemoteV1/UI/Window/ConnectionTreeWindow.cs
  mRemoteV1/mRemoteV1.csproj
Labels: Enhancement
