Repository mRemoteNG/mRemoteNG, pull requests merged in 2023-03, with the labels that each got.

#2362 Fix use of sql database
  mRemoteNG/Config/Serializers/ConnectionSerializers/MsSql/DataTableSerializer.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/MsSql/SqlDatabaseMetaDataRetriever.cs
  mRemoteNG/Config/Serializers/Versioning/SqlDatabaseVersionVerifier.cs
  mRemoteNG/Config/Serializers/Versioning/SqlVersion26To27Upgrader.cs
  mRemoteNG/Config/Serializers/Versioning/SqlVersion27To28Upgrader.cs
  mRemoteNG/Config/Serializers/Versioning/SqlVersion28To29Upgrader.cs
  mRemoteNGDocumentation/mssql_db_setup.sql
  mRemoteNGDocumentation/mysql_db_setup.sql
  mRemoteNGDocumentation/sql_configuration.rst
Labels: Fixed, DBs, 1.77.3

#2364 update sql usage doc
  mRemoteNGDocumentation/sql_configuration.rst
Labels: Fixed, Documentation, DBs, 1.77.3

#2369 Update find_vstool.ps1
  Tools/find_vstool.ps1
Labels: Project Infrastructure, 1.77.3

#2370 Update FilesFragment.wxs
  mRemoteNGInstaller/Installer/Fragments/FilesFragment.wxs
Labels: Project Infrastructure, 1.77.3

#2371 Update mRemoteNG.sln
  mRemoteNG.sln
Labels: Project Infrastructure, 1.77.3

#2374 add rdc10 protocol
  mRemoteNG/Connection/Protocol/RDP/RdpProtocol10.cs
  mRemoteNG/Connection/Protocol/RDP/RdpProtocolFactory.cs
  mRemoteNG/Connection/Protocol/RDP/RdpVersion.cs
Labels: Enhancement, UI/UX, RDP, 1.77.3

#2373 Update MessageFocusDecorator.cs
  mRemoteNG/Messages/WriterDecorators/MessageFocusDecorator.cs
Labels: Enhancement, UI/UX, 1.77.3, bug-fix

#2372 fix exception when no putty sessions exist
  mRemoteNG/Config/Putty/AbstractPuttySessionsProvider.cs
  mRemoteNG/Config/Putty/PuttySessionsRegistryProvider.cs
Labels: Putty, 1.77.3, bug-fix

#2377 Fix putty registry watcher
  mRemoteNG/Config/Putty/PuttySessionsRegistryProvider.cs
Labels: Putty, 1.77.3, bug-fix

#2378 appveyor build adjustment
  Tools/create_upg_chk_files.ps1
  Tools/postbuild_installer.ps1
  Tools/postbuild_mremoteng.ps1
  Tools/rename_and_copy_installer.ps1
  Tools/update_and_upload_website_release_json_file.ps1
Labels: Project Infrastructure, 1.77.3

#2379 additional appveyor change
  Tools/create_upg_chk_files.ps1
  Tools/postbuild_installer.ps1
  Tools/postbuild_mremoteng.ps1
  Tools/update_and_upload_website_release_json_file.ps1
Labels: Project Infrastructure, 1.77.3

#2380 appveyor build automation
  Tools/create_upg_chk_files.ps1
  Tools/find_vstool.ps1
  Tools/github_functions.ps1
  Tools/postbuild_installer.ps1
  Tools/postbuild_portable.ps1
  Tools/rename_and_copy_installer.ps1
  Tools/sign_binaries.ps1
  Tools/signfiles.ps1
  Tools/tidy_files_for_release.ps1
  Tools/update_and_upload_website_release_json_file.ps1
  Tools/validate_microsoft_tool.ps1
  Tools/verify_LargeAddressAware.ps1
  Tools/verify_binary_signatures.ps1
  Tools/zip_files.ps1
  mRemoteNG/mRemoteNG.csproj
Labels: Project Infrastructure, 1.77.3

#2386 Update mRemoteNG.csproj
  mRemoteNG/mRemoteNG.csproj
Labels: 1.77.3, Build

#2383 Update PuttySessionsRegistryProvider.cs
  mRemoteNG/Config/Putty/PuttySessionsRegistryProvider.cs
Labels: 1.77.3, bug-fix

#2387 Update ProtocolBase.cs
  mRemoteNG/Connection/Protocol/ProtocolBase.cs
Labels: 1.77.3, bug-fix

#2388 Delete RDPVersions.cs
  mRemoteNG/Connection/Protocol/RDP/RDPVersions.cs
Labels: TechnicalDebt, 1.77.3

#2391 Update mRemoteNG.csproj
  mRemoteNG/mRemoteNG.csproj
Labels: 1.77.3, Build

#2395 Improve Disk Drive Redirection
  mRemoteNG/App/Export.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Csv/CsvConnectionsDeserializerMremotengFormat.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Csv/CsvConnectionsSerializerMremotengFormat.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/MsSql/DataTableDeserializer.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionNodeSerializer28.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionsDeserializer.cs
  mRemoteNG/Config/Serializers/MiscSerializers/RemoteDesktopConnectionDeserializer.cs
  mRemoteNG/Config/Serializers/MiscSerializers/RemoteDesktopConnectionManagerDeserializer.cs
  mRemoteNG/Config/Serializers/Versioning/SqlDatabaseVersionVerifier.cs
  mRemoteNG/Config/Serializers/Versioning/SqlVersion29To30Upgrader.cs
  mRemoteNG/Connection/AbstractConnectionRecord.cs
  mRemoteNG/Connection/ConnectionInfo.cs
  mRemoteNG/Connection/ConnectionInfoInheritance.cs
  mRemoteNG/Connection/Protocol/RDP/RDPDiskDrives.cs
  mRemoteNG/Connection/Protocol/RDP/RdpProtocol.cs
  mRemoteNG/Language/Language.Designer.cs
  mRemoteNG/Language/Language.resx
  mRemoteNG/Properties/Settings.Designer.cs
  mRemoteNG/Schemas/mremoteng_confcons_v2_8.xsd
  mRemoteNG/UI/Controls/ConnectionInfoPropertyGrid/ConnectionInfoPropertyGrid.cs
  mRemoteNG/mRemoteNG.csproj
  mRemoteNGTests/Config/Serializers/MiscSerializers/RemoteDesktopConnectionDeserializerTests.cs
  mRemoteNGTests/Config/Serializers/MiscSerializers/RemoteDesktopConnectionManager27DeserializerTests.cs
  mRemoteNGTests/Config/Serializers/MiscSerializers/RemoteDesktopConnectionManagerDeserializerTests.cs
  mRemoteNGTests/Connection/AbstractConnectionInfoDataTests.cs
Labels: Enhancement, RDP, Windows, 1.77.3

#2397 Update ProgramRoot.cs
  mRemoteNG/App/ProgramRoot.cs
Labels: 1.77.3, bug-fix

#2400 Fix database columns and some tests
  mRemoteNG.lutconfig
  mRemoteNG/App/Info/ConnectionsFileInfo.cs
  mRemoteNG/App/Info/GeneralAppInfo.cs
  mRemoteNG/App/Initialization/StartupDataLogger.cs
  mRemoteNG/Config/Connections/Multiuser/RemoteConnectionsSyncronizer.cs
  mRemoteNG/Config/Connections/SaveConnectionsOnEdit.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Sql/SqlDatabaseMetaDataRetriever.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionNodeSerializer27.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionNodeSerializer28.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionSerializerFactory.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionsDeserializer.cs
  mRemoteNG/Config/Serializers/MiscSerializers/RemoteDesktopConnectionDeserializer.cs
  mRemoteNG/Config/Serializers/Versioning/SqlVersion29To30Upgrader.cs
  mRemoteNG/Connection/DefaultConnectionInfo.cs
  mRemoteNG/Schemas/mremoteng_confcons_v2_8.xsd
  mRemoteNGTests/Config/CredentialHarvesterTests.cs
  mRemoteNGTests/Config/Serializers/ConnectionSerializers/Xml/ValidateXmlSchemas.cs
  mRemoteNGTests/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionsDocumentCompilerTests.cs
  mRemoteNGTests/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionsDocumentEncryptorTests.cs
  mRemoteNGTests/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionsSerializerTests.cs
  mRemoteNGTests/Connection/DefaultConnectionInfoTests.cs
  mRemoteNGTests/IntegrationTests/XmlSerializationLifeCycleTests.cs
  mRemoteNGTests/TestHelpers/SerializableConnectionInfoAllPropertiesOfType.cs
  mRemoteNGTests/UI/Window/ConfigWindowTests/ConfigWindowGeneralTests.cs
Labels: DBs, 1.77.3, Tests, bug-fix

#2401 options pages size and position fixes
  mRemoteNG/UI/Forms/OptionsPages/AdvancedPage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/AdvancedPage.cs
  mRemoteNG/UI/Forms/OptionsPages/AppearancePage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/AppearancePage.resx
  mRemoteNG/UI/Forms/OptionsPages/BackupPage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/BackupPage.cs
  mRemoteNG/UI/Forms/OptionsPages/ConnectionsPage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/ConnectionsPage.cs
  mRemoteNG/UI/Forms/OptionsPages/ConnectionsPage.resx
  mRemoteNG/UI/Forms/OptionsPages/CredentialsPage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/CredentialsPage.resx
  mRemoteNG/UI/Forms/OptionsPages/OptionsPage.resx
  mRemoteNG/UI/Forms/OptionsPages/SecurityPage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/SecurityPage.cs
  mRemoteNG/UI/Forms/OptionsPages/SecurityPage.resx
  mRemoteNG/UI/Forms/OptionsPages/SqlServerPage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/SqlServerPage.cs
  mRemoteNG/UI/Forms/OptionsPages/SqlServerPage.resx
  mRemoteNG/UI/Forms/OptionsPages/StartupExitPage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/StartupExitPage.cs
  mRemoteNG/UI/Forms/OptionsPages/StartupExitPage.resx
  mRemoteNG/UI/Forms/OptionsPages/TabsPanelsPage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/TabsPanelsPage.resx
  mRemoteNG/UI/Forms/OptionsPages/ThemePage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/ThemePage.resx
  mRemoteNG/UI/Forms/OptionsPages/UpdatesPage.Designer.cs
  mRemoteNG/UI/Forms/OptionsPages/UpdatesPage.resx
  mRemoteNG/UI/Forms/frmOptions.Designer.cs
Labels: UI/UX, 1.77.3, bug-fix

#2410 Fix notification bug introduced
  mRemoteNG/App/Initialization/MessageCollectorSetup.cs
  mRemoteNG/Messages/MessageWriters/NotificationPanelMessageWriter.cs
  mRemoteNG/Messages/MessageWriters/TextLogMessageWriter.cs
  mRemoteNG/UI/Menu/msMain/ViewMenu.cs
  mRemoteNG/UI/Window/ConnectionWindow.cs
Labels: 1.77.3, bug-fix

#2411 fix log4net logging
  mRemoteNG/Properties/AssemblyInfo.cs
  mRemoteNG/Properties/AssemblyInfo.tt
Labels: 1.77.3, bug-fix

#2412 Update find_vstool.ps1
  Tools/find_vstool.ps1
Labels: Project Infrastructure, 1.77.3, Build

#2413 Fix running of unit tests
  ExternalConnectors/ExternalConnectors.csproj
  mRemoteNG/App/Logger.cs
  mRemoteNG/Config/Serializers/ConnectionSerializers/Sql/DataTableSerializer.cs
  mRemoteNG/mRemoteNG.csproj
  mRemoteNGSpecs/mRemoteNGSpecs.csproj
  mRemoteNGTests/mRemoteNGTests.csproj
Labels: 1.77.3, Tests

#2415 Update RdpProtocol8.cs
  mRemoteNG/Connection/Protocol/RDP/RdpProtocol8.cs
Labels: UI/UX, 1.77.3, bug-fix
