Repository mRemoteNG/mRemoteNG, pull requests merged in 2023-02, with the labels that each got.

#2341 Fix broken tests
  mRemoteNGTests/UI/Forms/OptionsPages/OptionsConnectionsPageTests.cs
  mRemoteNGTests/UI/Forms/OptionsPages/OptionsTabsPanelPageTests.cs
  mRemoteNGTests/UI/Window/ConfigWindowTests/ConfigWindowGeneralTests.cs
  mRemoteNGTests/UI/Window/ConfigWindowTests/ConfigWindowRdpSpecialTests.cs
Labels: Tests

#2340 set the default theme setting
  mRemoteNG/Properties/OptionsThemePage.Designer.cs
  mRemoteNG/Properties/OptionsThemePage.settings
Labels: Startup

#2352 SSH.NET Update
  CHANGELOG.md
  mRemoteNG/mRemoteNG.csproj
Labels: Enhancement, SSH, File system, 1.77.3
